export enum ALL_TOPICS {
  BOUNDARY_POINTA = "boundary_pointA",
  CAR_POSE = "car_pose",
  CENTER_CAMERA_FOV120_MARKS = "center_camera_fov120_marks",
  CENTER_CAMERA_FOV30_MARKS = "center_camera_fov30_marks",
  CONN_LIST = "conn_list",
  DPC_CONTROL_DEBUG = "dpc_control_debug",
  DPC_LFP_PLANNING_PLANLINE = "dpc_lfp_planning_planline",
  DPC_LFP_PLANNING_TRAJECTORY = "dpc_lfp_planning_trajectory",
  DPC_PLANNING_DEBUG_INFO = "dpc_planning_debug_info",
  DPC_PLANNING_EDGELINE = "dpc_planning_edgeline",
  DPC_PLANNING_OTHERLINE = "dpc_planning_otherline",
  DPC_PLANNING_REFERENCE_LINE = "dpc_planning_reference_line",
  DPC_PLANNING_TAG = "dpc_planning_tag",
  FUSION_GOP = "fusion_gop",
  HDMAP_FREE_SPACE = "hdmap Free Space",
  HDMAP_LANE_LINES = "hdmap Lane Lines",
  LEFT_FRONT_CAMERA_MARKS = "left_front_camera_marks",
  LEFT_REAR_CAMERA_MARKS = "left_rear_camera_marks",
  LOCALIZATION_GLOBAL_HISTORY_TRAJECTORY = "localization_global_history_trajectory",
  LOCALIZATION_LOCAL_HISTORY_TRAJECTORY = "localization_local_history_trajectory",
  LOCALIZATION_POSITION = "localization_position",
  LOCALMAP_CENTER_LINE = "localmap_center_line",
  LOCALMAP_CROSSWALK = "localmap_crosswalk",
  LOCALMAP_INFO = "localmap_info",
  LOCALMAP_JUNCTION = "localmap_junction",
  LOCALMAP_LANE_LANE = "localmap_lane_lane",
  LOCALMAP_LANE_LINE = "localmap_lane_line",
  LOCALMAP_LANE_SIGN_GROUP = "localmap_lane_sign_group",
  LOCALMAP_MAP_LANE_ID = "localmap_map_lane_id",
  LOCALMAP_MAP_LINE_ID = "localmap_map_line_id",
  LOCALMAP_OTHER_TRAFFIC_LIGHT = "localmap_other_traffic_light",
  LOCALMAP_OTHER_TRAFFIC_SIGN = "localmap_other_traffic_sign",
  LOCALMAP_POLE = "localmap_pole",
  LOCALMAP_ROAD_MARKER = "localmap_road_marker",
  LOCALMAP_SPEEDBUMP = "localmap_speedbump",
  LOCALMAP_STOP_LINE = "localmap_stop_line",
  LOCALMAP_TRAFFIC_LIGHT = "localmap_traffic_light",
  LOCALMAP_TRAFFIC_LIGHT_GROUP = "localmap_traffic_light_group",
  LOCALMAP_TRAFFIC_SIGN = "localmap_traffic_sign",
  LOCALMAP_TRAFFIC_SIGN_GROUP = "localmap_traffic_sign_group",
  MEMDRIVE_REF_ROUTE_TRAJECTORY = "memdrive_ref_route_trajectory",
  MEMDRIVE_REF_TRAJECTORY = "memdrive_ref_trajectory",
  MONITOR_REPORT = "monitor_report",
  ODOMETRY_INFO = "odometry_info",
  PERCEPTION_CAMERA_FRONT = "perception_camera_front",
  PERCEPTION_CAMERA_FRONT_PERCEPTION_CAMERA_CAR_LIGHT = "perception_camera_front perception_camera_car_light",
  PERCEPTION_CAMERA_NV = "perception_camera_nv",
  PERCEPTION_CAMERA_NV_PERCEPTION_CAMERA_CAR_LIGHT = "perception_camera_nv perception_camera_car_light",
  PERCEPTION_CAMERA_ROADLINES_CENTER_CAMERA_FOV120 = "perception_camera_roadlines center_camera_fov120",
  PERCEPTION_CAMERA_ROADLINES_CENTER_CAMERA_FOV30 = "perception_camera_roadlines center_camera_fov30",
  PERCEPTION_CAMERA_ROADLINES_NV_CAMERAS = "perception_camera_roadlines nv_cameras",
  PERCEPTION_FUSION_OBJECT = "perception_fusion_object",
  PERCEPTION_FUSION_PERCEPTION_FUSION_CAR_LIGHT = "perception_fusion perception_fusion_car_light",
  PERCEPTION_FUSION_PERCEPTION_FUSION_OBJECT = "perception_fusion /perception/fusion/object",
  PERCEPTION_OBSTACLE_FUSION = "perception_obstacle_fusion",
  PERCEPTION_RADAR_FRONT = "perception_radar_front",
  PILOTHMI_CROSS_WALK_LOCAL = "pilothmi_cross_walk_local",
  PILOTHMI_DRIVE_INFO = "pilothmi_drive_info",
  PILOTHMI_ENVM_INFO = "pilothmi_envm_info",
  PILOTHMI_IMAGE_OVERLAY = "pilothmi_image_overlay",
  PILOTHMI_LANE_LINE = "pilothmi_lane_line",
  PILOTHMI_LANE_LINES = "pilothmi_lane_lines",
  PILOTHMI_PERCEPTION_ENVODD = "pilothmi_perception_envodd",
  PILOTHMI_PERCEPTION_OBSTACLE_FUSION_OBJECT = "pilothmi_perception_obstacle_fusion object",
  PILOTHMI_PERCEPTION_OBSTACLE_LOCAL = "pilothmi_perception_obstacle_local",
  PILOTHMI_PERCEPTION_TRAFFIC_PARTICIPANT_FUSION_OBJECT = "pilothmi_perception_traffic_participant_fusion object",
  PILOTHMI_PILOT_PLANNING_TRAJECTORY = "pilothmi_pilot_planning_trajectory",
  PILOTHMI_PLANNING_LINES_INFO = "pilothmi_planning_lines_info",
  PILOTHMI_STOP_LINE = "pilothmi_stop_line",
  PILOTHMI_VEHICLE_REPORT = "pilothmi_vehicle_report",
  REAR_CAMERA_MARKS = "rear_camera_marks",
  RIGHT_FRONT_CAMERA_MARKS = "right_front_camera_marks",
  RIGHT_REAR_CAMERA_MARKS = "right_rear_camera_marks",
  SDMAP_ENDLINK_NODE = "sdmap_endlink_node",
  SDMAP_GEOMETRY_LINE = "sdmap_geometry_line",
  SDMAP_NAV_LINE = "sdmap_nav_line",
  SDMAP_STARTLINK_NODE = "sdmap_startlink_node",
  SENSOR_CAN_FRAME_SEQUENCE_CHART = "sensor_can_frame_sequence_chart",
  SENSOR_CAN_TIMESTAMP_CHART = "sensor_can_timestamp_chart",
  SENSOR_CAN_VEHICLE_MAP_CHART = "sensor_can_vehicle_map_chart",
  SENSOR_CAN_WHEEL_SPEED_CHART = "sensor_can_wheel_speed_chart",
  SENSOR_IMU_ACCEL_CHART = "sensor_imu_accel_chart",
  SENSOR_IMU_FRAME_SEQUENCE_CHART = "sensor_imu_frame_sequence_chart",
  SENSOR_IMU_GYRO_CHART = "sensor_imu_gyro_chart",
  SENSOR_IMU_TIMESTAMP_CHART = "sensor_imu_timestamp_chart",
  SENSOR_INS_INFO = "sensor_ins_info",
  SENSOR_VEHICLE_INFO = "sensor_vehicle_info",
  SENSOR_VEHICLE_STAT = "sensor_vehicle_stat",
  TOPIC_INFO = "topicInfo",
  VEHICLE_ALARM_INFO = "VehicleAlarmInfo",
  VISUALIZER_SERVER_FPS = "visualizer_server_fps"
}

export const VIRTUAL_RENDER_MAP = {
  arrow: [
    ALL_TOPICS.FUSION_GOP,
    ALL_TOPICS.LOCALIZATION_GLOBAL_HISTORY_TRAJECTORY,
    ALL_TOPICS.LOCALIZATION_LOCAL_HISTORY_TRAJECTORY,
    ALL_TOPICS.PERCEPTION_CAMERA_FRONT,
    ALL_TOPICS.PERCEPTION_CAMERA_NV,
    ALL_TOPICS.PERCEPTION_FUSION_OBJECT,
    ALL_TOPICS.PERCEPTION_FUSION_PERCEPTION_FUSION_OBJECT,
    ALL_TOPICS.PERCEPTION_OBSTACLE_FUSION,
    ALL_TOPICS.PERCEPTION_RADAR_FRONT
  ],
  car_pose: [ALL_TOPICS.CAR_POSE],
  crosswalk: [ALL_TOPICS.LOCALMAP_CROSSWALK],
  ellipse: [
    ALL_TOPICS.BOUNDARY_POINTA,
    ALL_TOPICS.LOCALIZATION_POSITION,
    ALL_TOPICS.SDMAP_ENDLINK_NODE,
    ALL_TOPICS.SDMAP_STARTLINK_NODE
  ],
  fixedPolygon: [
    ALL_TOPICS.PERCEPTION_CAMERA_FRONT_PERCEPTION_CAMERA_CAR_LIGHT,
    ALL_TOPICS.PERCEPTION_CAMERA_NV_PERCEPTION_CAMERA_CAR_LIGHT,
    ALL_TOPICS.PERCEPTION_FUSION_PERCEPTION_FUSION_CAR_LIGHT
  ],
  freespace: [
    ALL_TOPICS.HDMAP_FREE_SPACE,
    ALL_TOPICS.LOCALMAP_JUNCTION,
    ALL_TOPICS.LOCALMAP_LANE_LANE
  ],
  poleModel: [ALL_TOPICS.LOCALMAP_POLE],
  polygon: [
    ALL_TOPICS.FUSION_GOP,
    ALL_TOPICS.PERCEPTION_CAMERA_FRONT,
    ALL_TOPICS.PERCEPTION_CAMERA_NV,
    ALL_TOPICS.PERCEPTION_FUSION_OBJECT,
    ALL_TOPICS.PERCEPTION_FUSION_PERCEPTION_FUSION_OBJECT,
    ALL_TOPICS.PERCEPTION_OBSTACLE_FUSION
  ],
  polyline: [
    ALL_TOPICS.DPC_LFP_PLANNING_PLANLINE,
    ALL_TOPICS.DPC_LFP_PLANNING_TRAJECTORY,
    ALL_TOPICS.DPC_PLANNING_DEBUG_INFO,
    ALL_TOPICS.DPC_PLANNING_EDGELINE,
    ALL_TOPICS.DPC_PLANNING_OTHERLINE,
    ALL_TOPICS.DPC_PLANNING_REFERENCE_LINE,
    ALL_TOPICS.HDMAP_LANE_LINES,
    ALL_TOPICS.LOCALMAP_CENTER_LINE,
    ALL_TOPICS.LOCALMAP_LANE_LINE,
    ALL_TOPICS.LOCALMAP_SPEEDBUMP,
    ALL_TOPICS.LOCALMAP_STOP_LINE,
    ALL_TOPICS.MEMDRIVE_REF_ROUTE_TRAJECTORY,
    ALL_TOPICS.MEMDRIVE_REF_TRAJECTORY,
    ALL_TOPICS.PERCEPTION_CAMERA_ROADLINES_CENTER_CAMERA_FOV120,
    ALL_TOPICS.PERCEPTION_CAMERA_ROADLINES_CENTER_CAMERA_FOV30,
    ALL_TOPICS.PERCEPTION_CAMERA_ROADLINES_NV_CAMERAS,
    ALL_TOPICS.SDMAP_GEOMETRY_LINE,
    ALL_TOPICS.SDMAP_NAV_LINE
  ],
  roadMarkerModel: [ALL_TOPICS.LOCALMAP_ROAD_MARKER],
  target: [
    ALL_TOPICS.DPC_PLANNING_DEBUG_INFO,
    ALL_TOPICS.FUSION_GOP,
    ALL_TOPICS.PERCEPTION_CAMERA_FRONT,
    ALL_TOPICS.PERCEPTION_CAMERA_NV,
    ALL_TOPICS.PERCEPTION_FUSION_OBJECT,
    ALL_TOPICS.PERCEPTION_FUSION_PERCEPTION_FUSION_OBJECT,
    ALL_TOPICS.PERCEPTION_OBSTACLE_FUSION,
    ALL_TOPICS.PERCEPTION_RADAR_FRONT
  ],
  text_sprite: [
    ALL_TOPICS.LOCALMAP_MAP_LANE_ID,
    ALL_TOPICS.LOCALMAP_MAP_LINE_ID
  ],
  trafficLightModel: [
    ALL_TOPICS.LOCALMAP_OTHER_TRAFFIC_LIGHT,
    ALL_TOPICS.LOCALMAP_TRAFFIC_LIGHT
  ],
  trafficSignalModel: [
    ALL_TOPICS.LOCALMAP_OTHER_TRAFFIC_SIGN,
    ALL_TOPICS.LOCALMAP_TRAFFIC_SIGN
  ]
} as const;

export const AUGMENTED_RENDER_MAP = {
  car_pose: [ALL_TOPICS.CAR_POSE],
  crosswalk: [ALL_TOPICS.PILOTHMI_CROSS_WALK_LOCAL],
  freespace: [ALL_TOPICS.HDMAP_FREE_SPACE, ALL_TOPICS.PILOTHMI_LANE_LINE],
  obstacleModel: [
    ALL_TOPICS.PILOTHMI_PERCEPTION_OBSTACLE_FUSION_OBJECT,
    ALL_TOPICS.PILOTHMI_PERCEPTION_OBSTACLE_LOCAL
  ],
  participantModel: [
    ALL_TOPICS.PILOTHMI_PERCEPTION_TRAFFIC_PARTICIPANT_FUSION_OBJECT
  ],
  polyline: [
    ALL_TOPICS.PILOTHMI_LANE_LINES,
    ALL_TOPICS.PILOTHMI_PLANNING_LINES_INFO,
    ALL_TOPICS.PILOTHMI_PILOT_PLANNING_TRAJECTORY,
    ALL_TOPICS.PILOTHMI_STOP_LINE
  ],
  poleModel: [ALL_TOPICS.LOCALMAP_POLE],
  roadMarkerModel: [ALL_TOPICS.LOCALMAP_ROAD_MARKER],
  trafficLightModel: [
    ALL_TOPICS.LOCALMAP_OTHER_TRAFFIC_LIGHT,
    ALL_TOPICS.LOCALMAP_TRAFFIC_LIGHT
  ],
  trafficSignalModel: [
    ALL_TOPICS.LOCALMAP_OTHER_TRAFFIC_SIGN,
    ALL_TOPICS.LOCALMAP_TRAFFIC_SIGN
  ]
} as const;

export const OTHER_INFO_MAP = {
  LaneSignGroup: [ALL_TOPICS.LOCALMAP_LANE_SIGN_GROUP],
  TrafficLightGroup: [ALL_TOPICS.LOCALMAP_TRAFFIC_LIGHT_GROUP],
  TrafficSignGroup: [ALL_TOPICS.LOCALMAP_TRAFFIC_SIGN_GROUP],
  chart: [
    ALL_TOPICS.SENSOR_CAN_FRAME_SEQUENCE_CHART,
    ALL_TOPICS.SENSOR_CAN_TIMESTAMP_CHART,
    ALL_TOPICS.SENSOR_CAN_VEHICLE_MAP_CHART,
    ALL_TOPICS.SENSOR_CAN_WHEEL_SPEED_CHART,
    ALL_TOPICS.SENSOR_IMU_ACCEL_CHART,
    ALL_TOPICS.SENSOR_IMU_FRAME_SEQUENCE_CHART,
    ALL_TOPICS.SENSOR_IMU_GYRO_CHART,
    ALL_TOPICS.SENSOR_IMU_TIMESTAMP_CHART
  ],
  conn_list: [ALL_TOPICS.CONN_LIST],
  data: [ALL_TOPICS.VISUALIZER_SERVER_FPS],
  image: [
    ALL_TOPICS.CENTER_CAMERA_FOV120_MARKS,
    ALL_TOPICS.CENTER_CAMERA_FOV30_MARKS,
    ALL_TOPICS.LEFT_FRONT_CAMERA_MARKS,
    ALL_TOPICS.LEFT_REAR_CAMERA_MARKS,
    ALL_TOPICS.REAR_CAMERA_MARKS,
    ALL_TOPICS.RIGHT_FRONT_CAMERA_MARKS,
    ALL_TOPICS.RIGHT_REAR_CAMERA_MARKS
  ],
  monitorData: [ALL_TOPICS.MONITOR_REPORT],
  pilotDrive: [ALL_TOPICS.PILOTHMI_DRIVE_INFO],
  pilot_image_overlay: [ALL_TOPICS.PILOTHMI_IMAGE_OVERLAY],
  statusInfo: [
    ALL_TOPICS.PILOTHMI_ENVM_INFO,
    ALL_TOPICS.PILOTHMI_VEHICLE_REPORT
  ],
  text: [
    ALL_TOPICS.DPC_CONTROL_DEBUG,
    ALL_TOPICS.DPC_PLANNING_TAG,
    ALL_TOPICS.LOCALMAP_INFO,
    ALL_TOPICS.ODOMETRY_INFO,
    ALL_TOPICS.SENSOR_INS_INFO
  ],
  topicInfo: [
    ALL_TOPICS.PERCEPTION_FUSION_PERCEPTION_FUSION_OBJECT,
    ALL_TOPICS.PERCEPTION_RADAR_FRONT
  ],
  vehicleAlarmInfo: [ALL_TOPICS.VEHICLE_ALARM_INFO],
  vehicle_info: [ALL_TOPICS.SENSOR_VEHICLE_INFO],
  vehicle_stat: [ALL_TOPICS.SENSOR_VEHICLE_STAT],
  Weather: [ALL_TOPICS.PILOTHMI_PERCEPTION_ENVODD]
} as const;
